default:
 branch: 'powerkvm-v3.1.1'
 work_dir: 'workspace'
 result_dir: 'result'
 build_versions_repository_url: "https://github.com/open-power-host-os/versions.git"
 build_version: 'master'
 distro_name: 'CentOS'
 distro_version: '7'
 arch_and_endianness: 'ppc64le'
 release_notes_repo_url: "https://github.com/open-power-host-os/open-power-host-os.github.io.git"
 release_notes_repo_branch: "master"
 mock_binary: "/usr/bin/mock"
 mock_config:
  CentOS:
   '7': "./mock_configs/CentOS/7/CentOS-7-ppc64le.cfg"
 mock_args:
   # If the system has less RAM than required, the plugin will be disabled
   "--enable-plugin=tmpfs
   --plugin-option=tmpfs:keep_mounted=True
   --plugin-option=tmpfs:max_fs_size=32g
   --plugin-option=tmpfs:required_ram_mb=39800"
 commit_updates: True
 push_updates: True
 force_rebuild: False
iso:
    iso_name: "OpenPOWER-Host_OS"
    mock_config: "./mock_configs/CentOS/7/spin-iso-CentOS-7-ppc64le.cfg"
    packages_dir: "result/packages/latest"
    kickstart_file: "host-os.ks"
    hostos_packages_groups:
        virtualization-hypervisor:
            - "SLOF"
            - "docker"
            - "ginger"
            - "ginger-base"
            - "golang"
            - "kernel"
            - "kimchi"
            - "libvirt"
            - "libvirt-daemon-kvm"
            - "libvirt-daemon-lxc"
            - "libvirt-daemon-qemu"
            - "libvirt-devel"
            - "libvirt-docs"
            - "libvirt-lock-sanlock"
            - "libvirt-login-shell"
            - "libvirt-nss"
            - "libvpd"
            - "lsvpd"
            - "novnc"
            - "ppc64-diag"
            - "qemu"
            - "qemu-guest-agent"
            - "qemu-kvm-tools"
            - "servicelog"
            - "sos"
            - "systemtap"
            - "wok"
    package_group_list:
        - "@base"
        - "@core"
        - "@debugging"
        - "@virtualization-hypervisor"
        - "@virtualization-tools"
        - "@network-file-system-client"
        - "@remote-system-management"
        - "@virtualization-platform"
        - "grub2"
    mock_spin_repo:
        name: "hostos"
        dir: "/host-os-repo"
    distro_repo_url:
        base: "http://mirror.centos.org/altarch/7/os/ppc64le/"
        updates: "http://mirror.centos.org/altarch/7/updates/ppc64le/"
        extras: "http://mirror.centos.org/altarch/7/extras/ppc64le/"
        epel: "http://download.fedoraproject.org/pub/epel/7/ppc64le/"
