build-iso:
  automated_install_file: host-os.ks
  distro_repos:
  - name: base
    url: http://mirror.centos.org/altarch/7/os/ppc64le/
    url_type: baseurl
  - name: epel
    url: http://mirror.utexas.edu/epel/7/ppc64le/
    url_type: baseurl
  - name: extras
    url: http://mirror.centos.org/altarch/7/extras/ppc64le/
    url_type: baseurl
  - name: updates
    url: http://mirror.centos.org/altarch/7/updates/ppc64le/
    url_type: baseurl
  installable_environments:
    OpenPOWER Host OS RAS:
    - open-power-host-os-ras
    OpenPOWER Host OS all:
    - open-power-host-os-all
    OpenPOWER Host OS base:
    - open-power-host-os-base
    OpenPOWER Host OS container:
    - open-power-host-os-container
    OpenPOWER Host OS virtualization:
    - open-power-host-os-virt
    OpenPOWER Host OS virtualization management:
    - open-power-host-os-virt-management
  iso_name: Host_OS
  iso_repo_packages: []
  iso_repo_packages_groups:
  - OpenPOWER Host OS all
  - OpenPOWER Host OS base
  - OpenPOWER Host OS container
  - OpenPOWER Host OS virtualization
  - OpenPOWER Host OS virtualization management
  - OpenPOWER Host OS RAS
  iso_version: ''
  mock_args: --enable-plugin=tmpfs --plugin-option=tmpfs:keep_mounted=True --plugin-option=tmpfs:max_fs_size=32g
    --plugin-option=tmpfs:required_ram_mb=39800 --verbose
  mock_binary: /usr/bin/mock
  mock_iso_repo_name: host_os
  packages_dir: result/packages/latest
  pungi_args: --isfinal --nosource --nodebuginfo
  pungi_binary: /usr/bin/pungi
  result_dir: result
build-packages:
  force_rebuild: false
  keep_build_dir: false
  mock_args: --enable-plugin=tmpfs --plugin-option=tmpfs:keep_mounted=True --plugin-option=tmpfs:max_fs_size=32g
    --plugin-option=tmpfs:required_ram_mb=39800 --verbose
  mock_binary: /usr/bin/mock
  packages: []
  packages_metadata_repo_branch: master
  packages_metadata_repo_refspecs:
  - +refs/heads/*:refs/remotes/origin/*
  - +refs/pull/*:refs/remotes/origin/pr/*
  packages_metadata_repo_url: https://github.com/open-power-host-os/versions.git
  result_dir: result
  update_packages_repos_before_build: true
build-release-notes:
  commit_updates: true
  packages_metadata_repo_branch: master
  packages_metadata_repo_refspecs:
  - +refs/heads/*:refs/remotes/origin/*
  - +refs/pull/*:refs/remotes/origin/pr/*
  packages_metadata_repo_url: https://github.com/open-power-host-os/versions.git
  push_repo_branch: master
  push_repo_url: ''
  push_updates: true
  release_notes_repo_branch: master
  release_notes_repo_url: https://github.com/open-power-host-os/open-power-host-os.github.io.git
  update_packages_repos_before_build: true
  updater_email: ''
  updater_name: ''
host_os:
  architecture: ppc64le
  distro_name: CentOS
  distro_version: '7'
  http_proxy: ''
  log_size: 2097152
  verbose: false
  work_dir: workspace
update-metapackage:
  commit_updates: true
  packages_metadata_repo_branch: master
  packages_metadata_repo_refspecs:
  - +refs/heads/*:refs/remotes/origin/*
  - +refs/pull/*:refs/remotes/origin/pr/*
  packages_metadata_repo_url: https://github.com/open-power-host-os/versions.git
  push_repo_branch: master
  push_repo_url: ''
  push_updates: true
  update_packages_repos_before_build: true
  updater_email: ''
  updater_name: ''
update-versions:
  commit_updates: true
  packages: []
  packages_metadata_repo_branch: master
  packages_metadata_repo_refspecs:
  - +refs/heads/*:refs/remotes/origin/*
  - +refs/pull/*:refs/remotes/origin/pr/*
  packages_metadata_repo_url: https://github.com/open-power-host-os/versions.git
  push_repo_branch: master
  push_repo_url: ''
  push_updates: true
  update_packages_repos_before_build: true
  updater_email: ''
  updater_name: ''
